services:
  - type: web
    name: kith-platform
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: DATABASE_URL
        value: postgresql://db1_ubtp_user:WmY6Orqrf8sDeQd5UOM0eIYIYsXozvjr@dpg-d2rao9be5dus73d2l7vg-a.oregon-postgres.render.com/db1_ubtp
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET_NAME
        value: spiderman-v3-bucket1
      - key: AWS_REGION
        value: ap-southeast-1
      - key: CHROMA_DB_PATH
        value: /opt/render/project/src/chroma_db
      - key: ANONYMIZED_TELEMETRY
        value: FALSE
      - key: OPENAI_MODEL
        value: gpt-4
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true 