services:
  - type: web
    name: kith-platform
    env: python
    branch: ux-improvements
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent --workers 2 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DEFAULT_ADMIN_USER
        value: admin
      - key: DEFAULT_ADMIN_PASS
        generateValue: true
    healthCheckPath: /health
    healthCheckTimeout: 300

databases:
  - name: kith-platform-db
    databaseName: kith_platform
    user: kith_user
