name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kith-platform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 pre-commit

      - name: Lint (flake8)
        run: flake8

      - name: Format check (black)
        run: black --check .

      - name: Sort imports check (isort)
        run: isort --check-only .

      - name: Run tests
        env:
          OPENAI_API_KEY: ''
        run: pytest -q 